config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :chatrooms, only: [:new, :create, :show, :index] do
    resources :comments, only: [:create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chatroom
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.create(chatroom_params)
    redirect_to chatroom_path(@chatroom)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
  end

  def index
    chatrooms = Chatroom.all
    render json: chatrooms
  end

  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]
  
  def create
    chatroom = Chatroom.find(params[:chatroom_id])
    chatroom.comments.create(comment_params)
    SendCommentJob.perform_later(chatroom)
  end

  def index
    chatroom = Chatroom.find(params[:chatroom_id])
    render json: chatroom.comments
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @chatrooms = Chatroom.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/chatrooms/new.html.erb
<div class="page-content green">
  <h1>New chatroom page</h1>

  <br/>

  <%= simple_form_for @chatroom, url: chatrooms_path do |f| %>
    <%= f.input :name %>
    <br/>
    <%= f.submit 'Start', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/chatrooms/show.html.erb
<div class="green page-content">
  <h1>Chatroom show page</h1>

  <h3><%= link_to "Home page", root_path, class: "green" %></h3>

  <h3><%= @chatroom.name %></h3>

  <%= react_component("Comments", { root_with_chatroom_id: polymorphic_url(@chatroom), chatroom: @chatroom }) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railschat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="page-content">
  <h3 class="green">Homepage</h3>

  <h3><%= link_to "Start a chatroom", new_chatroom_path, class: "green" %></h3>

  <br/><br/>

  <% @chatrooms.each do |chatroom| %>
    <h3><%= link_to chatroom.name, chatroom_path(chatroom), class: "green" %></h3>
    <br/>
  <% end %>

</div>